#!/bin/sh

# Set these paths appropriately

BIN=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/bin
CMD=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/cmd
LIB=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/middle-high-german-abbreviations-utf8
PARFILE=${LIB}/middle-high-german-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
