#!/bin/sh

# Set these paths appropriately

BIN=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/bin
CMD=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/cmd
LIB=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
