#!/bin/sh

# Set these paths appropriately

BIN=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/bin
CMD=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/cmd
LIB=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
