#!/bin/sh

# Set these paths appropriately

BIN=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/bin
CMD=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/cmd
LIB=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian-utf8.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
