#!/bin/sh

# Set these paths appropriately

BIN=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/bin
CMD=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/cmd
LIB=/home/ubuntu/Elections/twitter_elections/sentiment_analysis/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/galician-abbreviations-utf8
PARFILE=${LIB}/galician-utf8.par
MWLFILE=${LIB}/galician-mwls

$TOKENIZER -z -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
